name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for gradlew
      run: |
        if [ -f "gradlew" ]; then
          echo "gradlew found - making executable"
          chmod +x gradlew
        else
          echo "ERROR: gradlew not found!"
          echo "Available files:"
          ls -la
          exit 1
        fi

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build with Gradle
      run: |
        ./gradlew build --stacktrace --no-daemon || ./gradlew assembleDebug --stacktrace

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: app/build/outputs/
        retention-days: 3
